### PR TITLE
Fixes #460

### LINKED ISSUE #460: Strings with accents are wrongly sorted
As stated here: https://zola.discourse.group/t/how-to-sort-taxonomies-taking-in-account-accentuated-letters

We badly sort the strings with accents. "écriture" is sorted after "zola" for instance.

### PR DESCRIPTION
**Pull request by Geobert**
Fixes https://github.com/Keats/tera/issues/460

### CODE REVIEW

**Comment by Keats** [comment]
That looks good but I don't know what the param name should be, `deunicode` is very hard to understand :/
Can you update the docs as well to mention that argument?

**Comment by Geobert** [comment]
I agree that the param's name is not the best…
What about `lexicographical`? 
I was waiting your greenlight on the PR before updating the doc, will do it with the change of param's name :)

**Comment by Keats** [comment]
I did a bit of research right now and it seems this function is not going to work until you can pass a locale, see https://stackoverflow.com/questions/1097908/how-do-i-sort-unicode-strings-alphabetically-in-python

Unless there is something similar in Rust, I'm afraid this isn't going to be merged since it would be incorrect for some languages.

**Comment by Geobert** [comment]
I know Rust lack of collation support right now. But if this can't get merged I won't be able to use Zola…

**Comment by Keats** [comment]
Changing it later would be a breaking change though and anyone writing in Swedish or other language would rightly report that as a bug :/ I don't see a good way to solve that until Rust gets some collation crate

**Comment by Geobert** [comment]
Fair enough, feel free to close it :)

**Comment by Keats** [comment]
I'm closing the PR but i'll update the issue with the details and leave that open

**Pull request closed without merging**
