### PR TITLE
bumped lazy_static to 1.0

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
The appveyor test failures look unrelated?

**Comment by Keats** [comment]
Can you do the PR on the v0.11 branch instead? That will also make the appveyor error go away

**Comment by alex** [comment]
@Keats I changed teh base branch, and the diff looks ok, but it didn't trigger rerunning the tests :-/

**Comment by Keats** [comment]
Should be fine. You can also try the v0.11 from crates.io if you want, quite a few changes in it

**Pull request merged**
