### PR TITLE
Handle unresolvable keys

### PR DESCRIPTION
**Pull request by stephanbuys**
This is, perhaps, the start of handling missing keys without resorting to panic'ing the thread.

### CODE REVIEW

**Comment by stephanbuys** [comment]
Oh, and also a 'once' initialiser that allows specifying a single file, as opposed to walking a tree by default.

**Comment by Keats** [comment]
Hey thanks for the PR.

For error handling, it seems @synlestidae started with #3 using Option which is imo the right way to do it: `render` should return a Result and it shouldn't be possible to ignore it

For the once initialiser, could you expand on why you would want a single file rather than a directory? Loading only one file will mean that inheritance won't work with it so it could lead to users confusion since they might expect Tera to find the parent file, which it won't do (and probably will never do) and i'm a bit reluctant to put API that can't use 100% of tera capabilities

**Comment by stephanbuys** [comment]
@Keats, full disclosure, I'm a complete novice :smile: (but I'm willing to help if I can) , so if nothing else let me lay out some observations.

I agree it should return a Result, with the Err containing a hint why the render failed, but I would also argue for a 'ignore' mode, which the Jinja2 library supports, it kind of feeds into the second part...

There are other non-html consumers of Jinja2 such as Saltstack (and some of our own tools), which applies the power of it's template engine to non-html files. In our case we have template files marked with a special extension, in my tests I was '`glob`bing' for our template files and then just '`once`'ing the individual files, but maybe a better solution is to use "Glob" instead of "WalkDir", that way the user can achieve all of the power by using for example, `./templates/**`, or if the want to be specific `./templates/**/*.tpl` - I've used crate `glob` and it works nicely https://doc.rust-lang.org/glob/glob/index.html

**Comment by stephanbuys** [comment]
Just another note, I think @synlestidae 's is definitely on the right track, so please feel to close this pull request, perhaps just consider the `glob` comment.

**Comment by Keats** [comment]
I like the globbing aspect, created #8 to remember it. Would globbing avoid the need for the `once` method?

**Comment by stephanbuys** [comment]
@Keats yeah, with globbing you would be able to specify just one file if need be, I think it would cover most use-cases I can think of now. (Apologies, long winded way to say, yes - wont need 'once' anymore)

**Pull request closed without merging**
