### PR TITLE
Upgrade chrono

### PR DESCRIPTION
**Pull request by arjentz**
Upgrade `chrono` the newly released version. I only ran `cargo test` and `cargo fuzz ...` (to be completely honest; it is still running) in order to check that everything still works.

### CODE REVIEW

**Comment by arjentz** [comment]
I am aware of your plans to put every dependency behind its own feature flag. I still think that's a good idea (I am only using a handful), but I just wanted to get this updated as soon as possible.

**Comment by Keats** [comment]
Looking at the updated versions, we should be getting the new version automatically? No need for a change afaik.

**Comment by arjentz** [comment]
You're right, I missed that. However, wouldn't it be good to force the use of a non-vulnerable version?

**Review by Keats — APPROVED** [review]

**Comment by arjentz** [comment]
@Keats Thanks for the approval. Apparently the pipeline doesn’t succeed due to a too low MSRV. Do you want me to do anything about that?

**Comment by Keats** [comment]
You can either update it or I will do it

**Comment by Keats** [comment]
That's a hefty bump! Might bump the minor version of Tera when I release that

**Pull request merged**
