### PR TITLE
fix dir bug in windows

### PR DESCRIPTION
**Pull request by daogangtang**
fix dir bug in windows

### CODE REVIEW

**Comment by Keats** [comment]
What's the bug? I thought Path was handling both windows and unix paths?

**Comment by daogangtang** [comment]
hi, when find templates on windows, it will generate "views\\index.html" key and such as. so need to replace the key, to '/', to keep the same code as linux in business.

**Comment by Keats** [comment]
I see, thanks.
Can you squash the commits and remove the commented out line please?

**Comment by daogangtang** [comment]
ok, tonight do it.

**Pull request closed without merging**
