### PR TITLE
Implemented filter sections

### PR DESCRIPTION
**Pull request by dswd**
This implements the filter sections from #102.
According to the tests it seems to work fine. However I am pretty unsure about the parser modifications as I wrote this part mostly by trial and error.

### CODE REVIEW

**Comment by Keats** [comment]
Looks good!

Can you add a section in the README about it and a failing test in `tests/render_fails.rs` for something like:
```jinja2
{% filter round %}
hello
{% endfilter %}
```

**Comment by Keats** [comment]
Thanks!

**Comment by SergioBenitez** [comment]
This doesn't work correctly. Anything after an `endfilter` tag is omitted from the rendered template. For instance, if we have the following template:

```jinja
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width" />
      <title>Tera Filter Section</title>
   </head>
   <body>
      {% filter my_filter %}
         Hello.
      {% endfilter %}
   </body>
</html>
```

With the following helper:

```rust
fn helper(value: Value, map: HashMap<String, Value>) -> tera::Result<Value> {
    Ok(value)
}
```

This renders:

```html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width" />
      <title>Tera Filter Section</title>
   </head>
   <body>

         Hello.
```

**Comment by Keats** [comment]
Ah damn... I'll fix that in the next release

**Comment by Keats** [comment]
It's fixed in master, i'll release along with a couple of other things next week

**Pull request merged**
