### PR TITLE
Addslashes filter implemented

### PR DESCRIPTION
**Pull request by orhanbalci**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
oh god, so many merges

**Comment by Keats** [comment]
Can you add the testcases from https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/template_tests/filter_tests/test_addslashes.py as well @orhanbalci please?

@nabijaczleweli github has squash and merge no so that's not a big issue but I'd recommend @orhanbalci to `git reset --hard` on my master and cherrypick `6529c98` on top, easier than merging!

**Comment by orhanbalci** [comment]
@Keats should we also escape backslashes?

**Comment by Keats** [comment]
I'd say yes if that's what django is doing

**Comment by orhanbalci** [comment]
@Keats  testcases added

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
