### PR TITLE
Global functions

### PR DESCRIPTION
**Pull request by Keats**
I need to try making some global functions in Gutenberg to make sure the design is ok

### CODE REVIEW

**Comment by Keats** [comment]
@khorolets that should solve your `range` issue

@phil-opp that also contains the doc update for macros `self` and opens the way for the `get_page` function you mentioned on the gutenberg repo. That also opens the way to shortcodes like Twitter/Instagram in http://gohugo.io/extras/shortcodes/ where you can do a http request to an API from a template

@SergioBenitez does that fix @102 for you?

**Comment by mackwic** [comment]
This is great ! 👍

**Comment by 102** [comment]
@Keats it was #102, not @102 🌝

**Comment by Keats** [comment]
woops sorry!

**Pull request merged**
