### PR TITLE
Make batch template sources generic

### PR DESCRIPTION
**Pull request by avitex**
- Backwards compatible
- Friendly API for less allocations on the consumer side

Cheers!

### CODE REVIEW

**Comment by avitex** [comment]
CI failing, see #516

**Comment by Keats** [comment]
Can you add tests for example things you have in mind?

**Comment by avitex** [comment]
Not sure what value that adds. You've already got test coverage for `vec![]`. Would just be testing other `IntoIterator`s

**Comment by Keats** [comment]
I guess I was more curious about the usecase in practice.

**Comment by avitex** [comment]
That's fair enough. An example use-case would be building a list of templates to be used,
as shown here. https://github.com/avitex/mdbook-tera/blob/master/src/lib.rs#L61

Rather than having to `collect` and allocate a vector, I would just pass the iterator in :)

**Comment by Keats** [comment]
Good example, I'll merge that along the other PRs around the end of the week!

**Pull request merged**
