### PR TITLE
Add the `matching` tester

### PR DESCRIPTION
**Pull request by vojtechkral**
Thought it would be nice to have something like this ...

### CODE REVIEW

**Comment by Keats** [comment]
That's a pretty good idea, thanks!

**Comment by vojtechkral** [comment]
Glad you like it, fyi I'm leaving for vacation and won't be online for ~14 days, so there's plenty of time to sleep on it ...

**Comment by Keats** [comment]
No worries, it looks good already, just waiting to see if there are more changes coming for a new version

**Comment by vojtechkral** [comment]
:+1: :-)

**Pull request merged**
