### PR TITLE
add indent filter

### PR DESCRIPTION
**Pull request by untereiner**

### CODE REVIEW

**Review by Keats — APPROVED** [review]

**Comment by tomasklaen** [comment]
I'd like to suggest for the `width` argument to be renamed to `indentation`, which accept both string and a number input, where if it's a string, it'll be used as indentation as is, and if it's a number, it'll be converted into that number of spaces (just as it works now), similar to how `JSON.stringify()` indentation parameter works in JS.

That way we could not only use spaces as indentation, but tabs and anything else as well, such as `> `, `* `, `- `, etc...

**Comment by Keats** [comment]
I would rather have just the string and people have to write `"   "` if they want 3 spaces rather than a number

**Comment by untereiner** [comment]
@Keats Here is the requested change. Sorry It was a bit long

**Comment by Keats** [comment]
Happy with it @tomasklaen ?

**Comment by tomasklaen** [comment]
Yup.

**Pull request merged**
