### PR TITLE
Docs reorganize

### PR DESCRIPTION
**Pull request by paulcmal**
Hey, as discussed in #332 i started reorganizing the templates docs and added a third level for the navigation menu with toggle buttons. The usability could be improved, as currently expanding the submenu will scroll up/down to said submenu. I still consider it way clearer and better than it was before :)

I added exactly one sentence in the docs, in the Variables part:
```
If you'd like to define your own variables, see the [Assignments](#assignments) section.
````

One workaround for the scrolling issue could be to have all submenu anchors generated on the H1 level so that for opening any submenu inside for instance "Templates" the scrolling would stick on that level.

Any feedback? :)

### CODE REVIEW

**Comment by Keats** [comment]
Few comments:

- we need to remove `| reverse` in `docs.html` when iterating on `section.pages (forgot to do that myself)
- I would have every menu open instead of toggling them on and off
- `default` filter has the wrong heading level
- `Conditions (If)` -> `if`
- `Loops (For)` -> `for`
- Extending templates and having macros in it is confusing, I would rather have macros in Control Structures and remove the Extending template menu

**Comment by paulcmal** [comment]
The rest I'm 100% ok with but

> I would have every menu open instead of toggling them on and off

We can, but it's still a lot of information to browse (cognitively speaking). I think at some point it will really help to do something about it, whether breaking into more pages or this kind of third-level expansion. I mean, i understand that you like the (mostly) single-page docs. Wouldn't a `man` page would be appropriate for you? While letting us mere mortals use web-technologies to link pages together? :P

When i say "at some point" i mean the docs will only grow bigger. Even without features being added, there's already a lot to clarify and make more friendly to newcomers.

**Comment by paulcmal** [comment]
OK I did it this way. For the current page, the menu is 3-levels deep and doesn't have controls. For other pages, it's 2-levels deep with controls for the third level. Quick notes:
- Menu controls are invisible to screen readers (with `aria-hidden` property) so they can have a nice menu without additional cruft
- Navigation menu should be wrapped in a <nav> for accessibility purposes
- Menu expansion could take place with an camouflaged checkbox so as not to mess with scrolling

If the rest is okay with you I'll take care of those last two points before you can merge :)

**Comment by Keats** [comment]
Ah just noticed something: built-in {filters, tests, global functions} should be at the top level, there isn't really a good name to group them.

I still don't like the (+) approach though, it would work with JavaScript but doing it via CSS triggers anchor jumping and is not working properly on all pages. Also I would expect to be able to close by reclicking on the (+), which would have turned into a (-) probably. I don't believe we can get a satisfying UX without JS so I would remove it completely and leave the full menu open.
Another issue of not showing the full hierarchy is that I would need to click around to know where is what I am looking for: for example assignments  are under `Manipulating data` here but under `Control structures` in the Jinja2 docs.

**Comment by paulcmal** [comment]
> is not working properly on all pages

What's not working properly? Could you be more specific?

> triggers anchor jumping (…) would have turned into a (-)

I addressed those two issues in my latest commits. Is this outcome okay by your usual JS standards? :D

> I would need to click around

Unless you're on the templates page already, in which case the menu will be expanded already. Is it such a concern? Having too many entries in a menu is a real accessibility/usability concern. I'm not sure hesitating between two sections is such a big deal in comparison?

> built-in {filters, tests, global functions} should be at the top level

I'll address this in a next commit and then in my opinion the PR would be ready for merging, unless you have more concerns :)

**Comment by Keats** [comment]
After a small round of user testing:

- much better than before
- they expected clicking on the link (like Data structures) to show what's below because of the (+)
- to fix that, it would need a `cursor: pointer` and a hover state to make it different from the header.

From me:

- the footer needs a `position: fixed; bottom: 0;` otherwise it's floating around on pages with little content
- use square brackets instead (+) -> [+] imo
- now that builtins are at the top level, there is an entry for each filter/test/fn name which makes the menu waaaay too long. I would rather have some kind of hack to not show them in the menu.

> I think global functions implies there's non-global functions (other than macros) which is confusing. 

I agree, I'm considering ading a rename from global function to function for the v1 breaking changes.

**Comment by paulcmal** [comment]
> they expected clicking on the link (like Data structures) to show what's below

Should it? Personally, I've always found it an anti-pattern in navigation menus to try and click a page and suddenly many children pop up and mess with the layout, especially on mobile.

> a hover state

The best i could come up with is `font-weight: bolder;`. I've experimented other things but i'm not a proper graphics designer so i'll stick with that and let someone improve upon :)

> the footer

Sorry what footer are you referring to? I didn't notice any problems on Firefox on desktop, although responsive view is a disaster (that's a quest for another day :D). Do you have a screenshot or something?

> I would rather have some kind of hack to not show them in the menu.

How about having a `Built-in tools` top-level as in my original proposal? That was its whole purpose in the first place :)

> I'm considering ading a rename from global function to function

I'll change the heading to have it fit properly, and leave the actual content as is for the moment, if that's okay with you.

**Comment by Keats** [comment]
> Should it? Personally, I've always found it an anti-pattern in navigation menus to try and click a page and suddenly many children pop up and mess with the layout, especially on mobile.

I think it's because in many places the [+]/(+) is the way to expand and the click only does expansion, the title is not a link itself.

> Sorry what footer are you referring to?

I'll fix that and the responsiveness, don't worry about it.

> How about having a Built-in tools top-level as in my original proposal?

Maybe just call it Built-ins then

**Comment by paulcmal** [comment]
> in many places

True. Well anyway if that's a behavior you'd like to achieve in a theme some day, you just have to wrap the link in the label and the whole of it gets clickable :)

> Maybe just call it Built-ins then

Done. Any more concerns to address? If not feel free the squash the commits :)

**Comment by Keats** [comment]
Thanks!

**Comment by paulcmal** [comment]
:heart:

**Pull request merged**
