### PR TITLE
Fixes some documentation and adds more code examples.

### PR DESCRIPTION
**Pull request by xfbs**
Hey, awesome project!

I've noticed that the rustdoc could use a little polishing! I know you have the website too but I find myself always consulting the rustdocs while I'm working and so I figured I could put a little work into it. 

Does this look good to you? I have not gone through the entire crate, only fixes a few things here and there. Wanted to make sure this makes sense before putting too much time into it.

Cheers,
-Patrick

### CODE REVIEW

**Review by Keats — APPROVED** [review]
I like it! I wouldn't do more changes for now because v2 might change some APIs even though I expect most of the public API to be very similar.

**Comment by Keats** [comment]
Looks like there is a test to fix?

**Comment by xfbs** [comment]
> I like it! I wouldn't do more changes for now because v2 might change some APIs even though I expect most of the public API to be very similar.

Awesome! I'll hold off on new PRs then, until you guys get to v2? 

> Looks like there is a test to fix?

Looks like it, I think I just fixed it.

**Comment by Keats** [comment]
> I'll hold off on new PRs then, until you guys get to v2?

Yep it would be better. Thanks for that PR!

**Pull request merged**
